### PR TITLE
Promote redirects to prod-stable

### PR DESCRIPTION
**Pull request by astrozzc**
Copy paste the changes in stage-stable to prod-stable

### CODE REVIEW

**Comment by ryelo** [comment]
@astrozzc should this be targeted to the prod-stable branch?

**Comment by ziliantech** [comment]
> @astrozzc should this be targeted to the prod-stable branch?

Asa told me the branch is ci-beta and the change would be merged into prod.  Is this still true for prod-stable branch? @kruai

**Comment by astrozzc** [comment]
> @astrozzc should this be targeted to the prod-stable branch?

Asa told me the prs should be opened against ci-beta and it would get merged into prod. Is that still true for prod-stable? @kruai

**Comment by kruai** [comment]
@astrozzc That doesn't automatically happen; I manually merged your redirect PRs to all branches earlier. So yes, it makes sense for this change to go into ci-beta first, and then I (or any of the other codeowners) can merge it to the other branches.

When do you want these redirects to be merged? Is there a target window?

**Comment by astrozzc** [comment]
> @astrozzc That doesn't automatically happen; I manually merged your redirect PRs to all branches earlier. So yes, it makes sense for this change to go into ci-beta first, and then I (or any of the other codeowners) can merge it to the other branches.
> 
> When do you want these redirects to be merged? Is there a target window?

Oh oh! You are the hero behind the scene! I thought there is a pipeline merging that 😅 Thanks! Ryan might know more about the target window @ryelo

**Comment by ryelo** [comment]
We're targeting Monday morning around 8am. If we can open a PR for it, I can merge it at that time.

**Review by kruai — APPROVED** [review]
OK. If these redirects look good to you @ryelo, we can merge this and I'll cherry-pick to all non-prod branches. In the meantime @astrozzc you'll need to open a PR with these same changes to the prod-stable branch for Ryan to merge

**Comment by kruai** [comment]
Actually, since we're low on time, I'm going to merge this so we can make sure there are no issues deploying it to Akamai... if you review and see something wrong or missing, let @astrozzc know so he can make a follow-up PR (and fix his prod-stable PR).

**Pull request merged**
