### PR TITLE
Subscription watch openshift update

### PR DESCRIPTION
**Pull request by cdcabrera**
Add in for Subs Watch views OCP and Dedicated

@rblackbu @bclarhk

### CODE REVIEW

**Comment by cdcabrera** [comment]
Appears I was mistaken on the sub apps being available in stable, I'll close this down, rethink it. Is there a date/timeframe associated with sub apps being available in stable? @karelhala @ryelo

**Comment by ryelo** [comment]
the new IA will go out with the rest of the summit deliverables.

Targeting Friday 3/19 to finalize new IA nav 
Targeting Monday 4/12 for new IA + console LP cloud.redhat.com/beta 
Targeting 4/26 for new IA + console LP cloud.redhat.com

**Comment by cdcabrera** [comment]
@ryelo is that an indication we should probably rethink and wait for 3/19?

We've also got the PR for QA stable up... https://github.com/RedHatInsights/cloud-services-config/pull/438

**Comment by cdcabrera** [comment]
Closing this down per discussion with @karelhala see RHCLOUD-12690

**Pull request closed without merging**
