### PR TITLE
Consolidate Insights and RHEL

### PR DESCRIPTION
**Pull request by kruai**
Merge RHEL into Insights as per https://projects.engineering.redhat.com/browse/RHCLOUD-4222
Let me know if I need to change the order of any of the apps.

### CODE REVIEW

**Review by ryelo — CHANGES_REQUESTED** [review]
The order should go:

* dashboard
* Advisor
    * Rules
    * Topics
* Vulnerability
* Compliance
* Custom Policies (?)
* Drift Analysis
    * System Comparison
    * Baselines
* Subscriptions (?)
* System Patching (?)
* Inventory
* Remediations

**Comment by kruai** [comment]
> The order should go:
> 
> * dashboard
> * Advisor
>   
>   * Rules
>   * Topics
> * Vulnerability
> * Compliance
> * Custom Policies (?)
> * Drift Analysis
>   
>   * System Comparison
>   * Baselines
> * Subscriptions (?)
> * System Patching (?)
> * Inventory
> * Remediations

Does this imply that Advisor is becoming its own app, and that Rules and Topics are becoming its sub-apps?

**Comment by ryelo** [comment]
I believe so. That's what was given to me on the mocks. Let me follow up with Rob tomorrow.

**Comment by kruai** [comment]
That would be great. If they want the Insights app's stuff to use the ID "advisor", there might be some issues... they'll have to change their app's config as well

**Comment by kruai** [comment]
I've changed the config to reflect the mocks; we'll need to coordinate this merge with the ID update from Insights to Advisor

**Review by ryelo — APPROVED** [review]
Tagging @AllenBW so he is aware of these changes too

**Pull request merged**
