### PR TITLE
MGDSTRM-755 Add Red Hat OpenShift Streams for Managed Kafka

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
Hmm, not sure why this is failing - it seems unrelated to my changes.

**Comment by Hyperkid123** [comment]
@pmuir it seems that something was merged even though the CI has failed. I will modify the validator to accept this new attribute.

**Comment by Hyperkid123** [comment]
The config looks solid

**Comment by kruai** [comment]
Re-running the PR check with the schema update.

**Review by kruai — APPROVED** [review]

**Pull request merged**
