### PR TITLE
Add app services to qa-stable

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Review by ryelo — COMMENTED** [review]
Couple things here:

We probably want to go ahead and add this to ci-stable too. @kruai does ci-stable still auto sync with qa-stable + qaprodauth?

Also, do we want to add the sub apps in this PR too?

**Comment by kruai** [comment]
@ryelo Nope, ci-stable doesn't merge to qa-stable. These branches sync:
- ci-beta -> nightly-beta -> qa-beta -> stage-beta
- ci-stable -> nightly-stable
- qa-stable -> stage-stable

And I'm sure you're aware, but... because qaprodauth is the QA env with Prod auth, it gets updated when QA gets updated.

**Comment by ryelo** [comment]
Thanks @kruai

@karelhala my question still stands on if you want to add the sub apps in this PR too. I am opening a PR to update the README with the branch sync so everyone is aware 😄

**Comment by karelhala** [comment]
@ryelo good point! I've added it there.

**Pull request merged**
