### PR TITLE
Use just one record for app services API

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Comment by karelhala** [comment]
ping @wtrocki and @riccardo-forina to confirm if this is correct.

**Comment by wtrocki** [comment]
Seems fine

**Comment by riccardo-forina** [comment]
I think so? 👀 I suppose this can be tested on stage before going live right?

**Comment by Hyperkid123** [comment]
@riccardo-forina yup this will land in stage beta first

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
