### PR TITLE
NOTIF-363 Adding application services to prod-stable

### PR DESCRIPTION
**Pull request by theute**
@josejulio same as https://github.com/RedHatInsights/cloud-services-config/pull/953 , for `prod-stable`

### CODE REVIEW

**Comment by josejulio** [comment]
Looks good, but travis is failing. Are we missing anything @karelhala ?

**Comment by karelhala** [comment]
Looks like app services has an error in their config. Kinda courius hiw it got trough 🤔

**Comment by Hyperkid123** [comment]
@karelhala this one is missing `appID` https://github.com/RedHatInsights/cloud-services-config/blob/b2577d37de86e6b2405d882ca3e41577a6c86251/chrome/application-services-navigation.json#L65 let me fix that.

**Comment by Hyperkid123** [comment]
@theute is there a specific time you want this to be merged? Or should we merge once the CI is ok?

**Review by Hyperkid123 — APPROVED** [review]

**Comment by theute** [comment]
Can be merged now, thanks !

**Pull request merged**
