### PR TITLE
ON HOLD: Adds malware app support

### PR DESCRIPTION
**Pull request by AllenBW**
along with https://github.com/RedHatInsights/malware-detection-frontend/commit/22676de4f807cea55753224fe80cd3215a63e480 should allow for devs to dev again

### CODE REVIEW

**Review by karelhala — APPROVED** [review]

**Comment by karelhala** [comment]
@AllenBW can you please add `isHidden` to the validator?

**Comment by AllenBW** [comment]
yap doin doin 🤗

**Comment by AllenBW** [comment]
Screen Shot 2021-05-13 at 8 35 21 AM


Before we merge this one... should isHidden be placed on the root?  given the schema... i guess it can't.... not sure if app still showing up should be of concern or not 🤔

**Comment by karelhala** [comment]
@AllenBW just part of the `frontend` schema. The root one is for app information, whereas the `frontend` part is used mostly by navigation.

**Review by karelhala — APPROVED** [review]

**Pull request merged**
