### PR TITLE
mua to prod-stable

### PR DESCRIPTION
**Pull request by ryelo**
@Hyperkid123

### CODE REVIEW

**Review by kruai — APPROVED** [review]

**Comment by kruai** [comment]
@ryelo Should this be on hold, or is it ready to be merged?

**Comment by kruai** [comment]
Should probably also make a PR for qa-stable btw, to keep that env in sync

**Comment by ryelo** [comment]
Sorry, it's on hold. Making sure Martin sees it before merging

**Comment by ryelo** [comment]
@Hyperkid123 feel free to ack this and i'll remove the label and merge

**Comment by Hyperkid123** [comment]
@ryelo I can ACK but can't do the rest (no permissions)

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
