### PR TITLE
feat: adding acs to prod-beta

### PR DESCRIPTION
**Pull request by sachaudh**
This PR is to add the Advanced Cluster Security (ACS) app to the consoledot (`prod-beta`) environment

### CODE REVIEW

**Comment by sachaudh** [comment]
So I wanted to just confirm that this is ok. Our backend team has created a public Fleet Manager API that apparently uses sso.redhat.com to authenticate the user. Since running the development environment locally uses a staging environment, the  UI uses sso.stage.redhat.com to authenticate the user. The token would therefore not work with API calls. They suggested we use sso.redhat.com instead so I thought I could run the UI locally to use sso.redhat.com instead. I got that part to work, but noticed that I'd need to make this change to actually see the ACS page in the UI too

I also requested they try to use sso.stage.redhat.com so I'm waiting to see if it's possible. In the meantime, I wanted to try it this way just so I had a Plan B in case they could not

**Comment by karelhala** [comment]
Just FYI once this PR is merged the app will be visible on console.redhat.com/beta I would advise using the stage SSO and if not possible this as a fallback. We could also hide the navigation parts by some rules.

**Review by Hyperkid123 — APPROVED** [review]
Changes are good. @sachaudh can you please answer @karelhala question before we proceed with the deployment?

**Comment by sachaudh** [comment]
Looks like we can get it working on staging now, so we can close this pull request. No need to merge. Thanks! 🙏🏼

**Pull request closed without merging**
