### PR TITLE
Add manifests to prod-beta

### PR DESCRIPTION
**Pull request by joeldmyers**
We are ready to promote the first UI Manifests work to prod-beta and want to add Manifests to the side menu in prod-beta.

### CODE REVIEW

**Comment by ryelo** [comment]
Are you opening the app to all customers?

**Comment by joeldmyers** [comment]
Yes, that's correct, we are good to open this up to everyone on prod-beta; permissions are separately handled within the app.

**Comment by ryelo** [comment]
Perfect. You can go ahead and merge your dev code to prod-beta whenever you'd like. once we merge this, we'll get 404s on that page until you push it out.

**Comment by joeldmyers** [comment]
I actually just did that and it looks like it finished two minutes ago :) https://github.com/RedHatInsights/subscription-central-ui-build/tree/prod-beta

**Pull request merged**
