### PR TITLE
Fix IO Gathering Conditions Service apiName

### PR DESCRIPTION
**Pull request by juandspy**
Fix the IO gathering conditions service apiName to match this PR - https://github.com/RedHatInsights/insights-operator-gathering-conditions-service/pull/150.

Using [api/gathering](https://console.stage.redhat.com/beta/docs/api/gathering) instead of [api/insights-operator-gathering-conditions-service](https://console.stage.redhat.com/beta/docs/api/insights-operator-gathering-conditions-service).

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by juandspy** [comment]
@Hyperkid123 how can I track these changes from ci to prod?

**Comment by Hyperkid123** [comment]
@Hyperkid123  We usually cherry-pick commits to respective branches. These environments have separate history so there are no sync jobs between pre-prod and prod.

**Comment by juandspy** [comment]
@Hyperkid123 shall I wait for the changes to arrive to stage-beta, then manually check and then ask you to move to prod?

**Comment by juandspy** [comment]
@Hyperkid123 oh, I think it's already working in stage - https://console.stage.redhat.com/beta/docs/api/gathering . Feel free to cherry pick
- https://github.com/RedHatInsights/cloud-services-config/pull/1023
- https://github.com/RedHatInsights/cloud-services-config/pull/1152

into PROD.

**Comment by Hyperkid123** [comment]
I am gonna do it tomorrow morning if that is fine. I got meetings for the rest of the day.

**Comment by juandspy** [comment]
@Hyperkid123 sure. Just ping me once done so that I can check. Thanks a lot :)

**Comment by juandspy** [comment]
@Hyperkid123 I've checked and [api/gathering](https://console.redhat.com/api/gathering/v1/openapi.json) is working both in stage and prod, so we are free to proceed :)

**Comment by juandspy** [comment]
@Hyperkid123 thanks, it's working perfectly fine in PROD.

**Pull request merged**
