### PR TITLE
Update Subscription Reporting path

### PR DESCRIPTION
**Pull request by cdcabrera**
## Description
Subscription Reporting bundle minor path and id update.

@kruai @ryelo @karelhala

### CODE REVIEW

**Review by karelhala — APPROVED** [review]
Looking good! Just bear in mind that you will have to change app identification name as well here https://github.com/RedHatInsights/curiosity-frontend/blob/a4f7da75ee33bc61f6ffc5bf99e85c0d7938f590/.env#L2

**Comment by ryelo** [comment]
You'll also need to update https://github.com/RedHatInsights/curiosity-frontend/blob/a4f7da75ee33bc61f6ffc5bf99e85c0d7938f590/package.json#L19

**Comment by cdcabrera** [comment]
AWESOME! Good catch @karelhala @ryelo 

We've got our WIP PR up on the Curiosity side, looks like we forgot the `package.json` update =)
- https://github.com/RedHatInsights/curiosity-frontend/pull/73/files

**Review by kruai — APPROVED** [review]
Looks good!

**Pull request merged**
