### PR TITLE
feat(openshift): add federated module

### PR DESCRIPTION
**Pull request by redallen**
Complementing uhc-portal MR: https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/2354#note_2341223

### CODE REVIEW

**Review by karelhala — APPROVED** [review]

**Comment by karelhala** [comment]
I made a mistake, it should go the other way around. Once UHC MR is merged we can merge this one - https://github.com/RedHatInsights/cloud-services-config/pull/583

**Comment by redallen** [comment]
@karelhala The MR won't render unless this change is made in `main.yml`. Do we have a chicken and egg problem?

**Comment by ryelo** [comment]
We didn't actually revert it. This should still be in ci-beta. So yes, chicken and egg 😄

**Comment by redallen** [comment]
Ah wonderful! Should I open a new PR to change `qa` as well? That's what `uhc-portal` proxies against for local development. I don't know how long it takes to promote this merged PR to that branch...

**Comment by karelhala** [comment]
@ryelo not really, the UHC MR is missing crucial react-dom render. Without this the UI would be broken before the UHC MR is merged. The proposed sollution https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/2354#note_2344439 fixes the problem and users won't see any errors while we merge stuff around.

**Pull request merged**
