### PR TITLE
[ci-stable] Add nav link for Cost Management

### PR DESCRIPTION
**Pull request by dlabrecq**
Add Optimizations nav link for Cost Management

https://issues.redhat.com/browse/COST-3600

### CODE REVIEW

**Comment by karelhala** [comment]
We are no longer sending the config from this repository. We are in a process of migrating over to https://github.com/RedHatInsights/chrome-service-backend if you need this change to happen sooner please open a PR in that repository.

**Comment by Hyperkid123** [comment]
Yeah sorry for the delays. I wanted to send out a memo soon, but since this is not working in prod yet I am holding off.

**Comment by dlabrecq** [comment]
Thanks, I will move this over to the new repo

**Comment by Hyperkid123** [comment]
We should send an email and instructions tomorrow.

**Pull request closed without merging**
