### PR TITLE
Add insights-operator-gathering-conditions-service reference

### PR DESCRIPTION
**Pull request by Hyperkid123**
Original PR: https://github.com/RedHatInsights/cloud-services-config/pull/1023

These changes were lost after the sync job was fixed.

### CODE REVIEW

**Review by karelhala — APPROVED** [review]
Looking good! Just FYI https://github.com/RedHatInsights/cloud-services-config/pull/1023#issuecomment-1115878774 I think let's merge this one and proceed with URl update later on.

**Comment by juandspy** [comment]
Hey I think we can merge this already :) @Hyperkid123

**Comment by Hyperkid123** [comment]
@juandspy there is a conflict. I am unsure which is correct. Can you resolve it, please?

**Comment by Hyperkid123** [comment]
@juandspy the prod-stable already contained these changes. It just had the old name for the gathering subitem

**Pull request closed without merging**
