### PR TITLE
Adds trust frontend

### PR DESCRIPTION
**Pull request by AllenBW**
on /security/insights

### CODE REVIEW

**Review by karelhala — APPROVED** [review]
Are the `tilte`s correct? It will have bundle name `Insights Security` and in navigation there will be `Insights Security`, also shouldn't these be sentence case?

But overall nothing seems to be off.

**Comment by AllenBW** [comment]
@karelhala good call, looks like sentence case is correct, and we don't so much need a title override, so getting rid of that second one 👍

**Comment by karelhala** [comment]
Just to be sure, this is not used in any bundle as of right now, right? So inaccessible by users.

**Review by kruai — APPROVED** [review]

**Comment by kruai** [comment]
Everything looks good to me, too. Merging!

**Pull request merged**
