### PR TITLE
[prod-stable] Add ansible platform landing page

### PR DESCRIPTION
**Pull request by lgalis**
* Remove ansible root path from the ansible-dashboard

* Set the Ansible Dashboard as the default path for the ansible path (#650)

* Add ansible-dashboard group to ansible-dashboard (#659)

Co-authored-by: Karel Hala <khala@redhat.com>

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@lgalis @karelhala is this still relevant? When do we require this to be merged?

**Comment by lgalis** [comment]
@Hyperkid123 - wait for me to check with QE - will post an update here

**Comment by lgalis** [comment]
@Hyperkid123 - got the OQ from QE - please review/merge when you can

**Comment by lgalis** [comment]
@Hyperkid123 , @karelhala - got the OK from QE - please review/merge when you can

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
