### PR TITLE
Adding edge and console bundles

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Review by karelhala — APPROVED** [review]

**Review by Hyperkid123 — CHANGES_REQUESTED** [review]
@josejulio can you change the target branch to `ci-beta`? It will get synced to stage automaticlly.

**Comment by josejulio** [comment]
> @josejulio can you change the target branch to `ci-beta`? It will get synced to stage automaticlly.

I'll create a new PR that targets `ci-beta`. Changing target branch leads to multiple commits and some other changes.

**Comment by Hyperkid123** [comment]
@josejulio if we merge into the stage-beta, it will break the sync job we have on Jenkins.

**Comment by josejulio** [comment]
> @josejulio if we merge into the stage-beta, it will break the sync job we have on Jenkins.

I got distracted - sorry. No worries - I'll create other PR.

**Comment by josejulio** [comment]
Replaced by https://github.com/RedHatInsights/cloud-services-config/pull/1081

**Pull request closed without merging**
