### PR TITLE
Adds malware app support

### PR DESCRIPTION
**Pull request by AllenBW**
fixes https://issues.redhat.com/browse/YARA-65 (but till then local dev on yara is on hold)

identical to  #587 which loookkksssss gooooodddddd (n hidden)

### CODE REVIEW

**Comment by ryelo** [comment]
That Chrome commit is not on prod yet

**Comment by AllenBW** [comment]
@ryelo lets on hold this B till then 🙇

**Comment by AllenBW** [comment]
@ryelo circling back, looks like there was a prod update today, can this be merged?

**Comment by ryelo** [comment]
@AllenBW there was no chrome update today. If you're referring to the calendar, that's out of date due to summit releases, we'll restart that effort after hackathon.

**Comment by karelhala** [comment]
@AllenBW the check is present on prod-beta now. I believe that this is required from your team to be present on the prod-stable sooner rather than later, right? If that's the case we'll release new prod-stable of chrome as well.

**Comment by AllenBW** [comment]
Yer correct @karelhala ! sooner rather than later, but by no means immediately

**Comment by Hyperkid123** [comment]
@AllenBW @karelhala @ryelo Which commit are we talking about? Is this still relevant?

**Comment by AllenBW** [comment]
@Hyperkid123 the commit that ensures chrome obeys the isHidden flag

**Comment by Hyperkid123** [comment]
@AllenBW that is in prod-stable. So I assume we can merge?

**Comment by AllenBW** [comment]
yeah! @Hyperkid123  <3

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
