### PR TITLE
[CCXDEV-8023] Add v2 version to the aggregator

### PR DESCRIPTION
**Pull request by juandspy**
We have a second version of the API at https://console.redhat.com/api/insights-results-aggregator/v2/openapi.json. Let's start showing it too.

### CODE REVIEW

**Review by karelhala — APPROVED** [review]
Which one should be the default when clicking on the app's name?

**Review by joselsegura — APPROVED** [review]

**Review by tisnik — APPROVED** [review]
ok

**Comment by juandspy** [comment]
> @karelhala Which one should be the default when clicking on the app's name?

Which one is the default? The first one? I suppose it's ok. Not a big deal in my opinion

**Comment by juandspy** [comment]
@karelhala is this expected? 
image

I can't see no API doc in stage.

**Comment by karelhala** [comment]
@juandspy looks like you are not logged-in, I can access that URL. However looks like nested API doesn't have support for versioning. I'll update the app to support it.

**Comment by juandspy** [comment]
> @juandspy looks like you are not logged-in, I can access that URL. However looks like nested API doesn't have support for versioning. I'll update the app to support it.

@karelhala everytime I log in in the console, it logs me out once I enter the `/docs/api` page.

**Comment by juandspy** [comment]
@karelhala when you see the v2 API docs correctly in stage, feel free to move it to PROD :)

**Comment by juandspy** [comment]
Hi @karelhala , do we have any Jira we can track for the progress of this task to PROD?

**Comment by karelhala** [comment]
@juandspy the drive trough the environments should be done by the requesting team. We don't know when the release of your API supports the version on the given environment. If you want you can open a ticket for platform experience to help you trough it. That being said I am investigating why the version 2 is not listed in the table console.stage.redhat.com/beta/docs/api even though it is loaded from the main.yml config.

**Comment by juandspy** [comment]
> We don't know when the release of your API supports the version on the given environment.

@karelhala the v2 API has been running for month. It's just that we forgot to put it here :) Do I have to open a PR in `ci-stable` to move it to PROD stable?

**Comment by karelhala** [comment]
The release cycle is somewhat automated in this repository
```
ci-beta -> qa-beta -> stage-beta
ci-stable -> qa-stable -> stage-stable
```

So currently the API change is only visible in stage-beta console.stage.redhat.com/beta, you should open 3 additional PRs
* prod-beta (console.redhat.com/beta)
* ci-stable (to see the change in stage-stable console.stage.redhat.com)
* prod-stable (console.redhat.com)

**Pull request merged**
