### PR TITLE
Add Openshift Subscriptions Left Navigation

### PR DESCRIPTION
**Pull request by petli-openshift**
This PR is for review ONLY. Please do NOT merge!

The underlying "Subscription" page is still working in process.

### CODE REVIEW

**Comment by kruai** [comment]
Looks good to me - do you also want to remove it from the Staging bundle?
Also, just FYI that when this does get merged, it will only show up in Beta until you approve its merge to Stable. If that's what you were worried about by making it a WIP, I mean :)

**Comment by petli-openshift** [comment]
@kruai @ryelo ,
We've told to merge this PR. Could you also help merge to Stable? We want it alive in Production.
Thanks!

**Comment by kruai** [comment]
@petli-openshift: You actually don't need the `title` field since the `subscriptions` app is already defined elsewhere in the app. It would work either way, but I like to keep the config smaller if possible. If you remove the `title` field I'll approve and merge!

**Comment by petli-openshift** [comment]
@kruai I removed the `title` field. Could you review again? Thanks!

**Review by kruai — CHANGES_REQUESTED** [review]
I apologize for making you make another change, but this will currently only create a new menu item. Because `subscriptions` is currently deployed under `staging`, you'll have to update that as well. To work in the `openshift` bundle, it needs to have the path: `/openshift/subscriptions`
If you want `subscriptions` to exist both in the Staging bundle and the Openshift bundle, please add this path to the subscriptions app. If you want to move it out of Staging instead, you can just replace the existing frontend path.

**Comment by petli-openshift** [comment]
@kruai AFAIK the Subscriptions app in staging was not from us. let me confirm. I will get back to you asap.

**Comment by kruai** [comment]
Sure. It's totally cool if it stays in Staging for now; we can always remove it later. If you just want to add a new path until we figure out who needs it in Staging, that's fine with me :)

**Comment by petli-openshift** [comment]
@kruai thanks for helping out. For this PR, we want a link named as `Subscriptions` to https://cloud.redhat.com/openshift/subscriptions

I realized there's diff `subscriptions` app in staging. Pls let me know what I should do to avoid the ID conflicts

**Comment by kruai** [comment]
I'm going to approve this PR and merge it to ci-beta. You'll see the sidenav in that environment, but it may not work as expected during this time. I've created this Jira issue to track progress:
https://projects.engineering.redhat.com/browse/RHCLOUD-2405

**Pull request merged**
