### PR TITLE
add task management to menu insights

### PR DESCRIPTION
**Pull request by ShaiahWren**
Part of issue https://issues.redhat.com/browse/AAH-1332, this pr adds  an additional menu items "Task Management" to be visible on insights mode.

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
@ShaiahWren Hello. Can we get some mocks/docs/spreadsheet of these changes? There is a quite a lot of them and I haven't found anything in the linked Jira task.

This touches all apps in the bundle so it would be nice to get a bit more detail :slightly_smiling_face: .

**Comment by ShaiahWren** [comment]
Hey there @Hyperkid123, the changes you see are from a code formatter I use on a different project. My bad. Do you use any code formatters or linters that I should run instead?

**Comment by Hyperkid123** [comment]
@ShaiahWren I see. can you remove the formatting changes, please?

But still there seem to be a lot of nav changes that span across multiple different applications. I would still like to have some mocks or tickets so I would like to have something to compare the changes to.

**Review by Hyperkid123 — APPROVED** [review]
LGTM

**Comment by himdel** [comment]
|branch|name|url|PR|
|-|-|-|-|
|ci-beta|stage-beta|https://console.stage.redhat.com/beta/ansible/automation-hub/|#1208 (here, merged)|
|ci-stable|stage-stable|https://console.stage.redhat.com/ansible/automation-hub/|#1268 (merged)|
|prod-beta|prod-beta|https://console.redhat.com/beta/ansible/automation-hub/|#1269 (merged)|
|prod-stable|prod-stable|https://console.redhat.com/ansible/automation-hub/|#1270 (merged)|

(tracking issue: https://issues.redhat.com/browse/AAH-1874)

**Pull request merged**
