### PR TITLE
Updated Cost Management details navigation

### PR DESCRIPTION
**Pull request by dlabrecq**
Updated Cost Management details navigation to look like this mock:

Screen Shot 2020-03-18 at 2 05 00 PM

See https://projects.engineering.redhat.com/browse/RHCLOUD-5267

Note: this is needed for the prod release on 4/23 -- our code freeze is 3/30

### CODE REVIEW

**Review by kruai — COMMENTED** [review]
Have you tested this change locally? I want to approve, but this structure is unfamiliar and I'm worried we might have to refactor a bit.

**Comment by dlabrecq** [comment]
I'm unfamiliar with testing the config locally. However, the Cost Management routes have been merged and tested.

**Review by kruai — APPROVED** [review]
You can test locally by following [this section in the README](https://github.com/RedHatInsights/cloud-services-config#testing-your-changes-locally). 
I'm giving tentative approval for now; once you've tested and it works correctly, please let me know and I'll resolve conflicts & merge.

**Comment by dlabrecq** [comment]
@kruai I've tested the changes locally and resolved the merge conflict

**Pull request merged**
