### PR TITLE
Adds Systems sub-app to advisor, #218 dupe

### PR DESCRIPTION
**Pull request by AllenBW**
dupe https://github.com/RedHatInsights/cloud-services-config/pull/218

this is waiting for https://github.com/RedHatInsights/insights-chrome/pull/841

### CODE REVIEW

**Comment by kruai** [comment]
Please remove the "do not merge" label when this one is ready to go.

**Review by kruai — APPROVED** [review]

**Comment by AllenBW** [comment]
@kruai i got no permissions to add or remove anything 😢

**Comment by kruai** [comment]
Oh. Well in that case, just @ me and I'll do it lol

**Comment by AllenBW** [comment]
@kruai ok we're good to go on this!!

**Pull request merged**
