### PR TITLE
Landing nav updates

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-18708
Depends on: https://github.com/RedHatInsights/insights-chrome/pull/1855

Screen Shot 2022-04-26 at 8 25 13 AM

### CODE REVIEW

**Comment by epwinchell** [comment]
@Hyperkid123 Could you look at the test? Thanks.

**Comment by Hyperkid123** [comment]
@epwinchell there was a missing validator reference. I have added it. Also, there was an invalid appId in the landing nav for ansible. I have fixed that as well.

**Comment by epwinchell** [comment]
> @epwinchell there was a missing validator reference. I have added it. Also, there was an invalid appId in the landing nav for ansible. I have fixed that as well.

Thank you @Hyperkid123

**Comment by pmuir** [comment]
Changes needed to both beta and stable

**Comment by Hyperkid123** [comment]
@pmuir do we know when? And are you talking about production? Or pre-prod?

**Comment by pmuir** [comment]
I believe it needs to go to prod on the 6th May cc @tiffanynolan

**Comment by Hyperkid123** [comment]
> I believe it needs to go to prod on the 6th May cc @tiffanynolan

@pmuir As this PR is only for pre-prod (stage/qaproduath) I would like to merge it before the summit code freeze. And we can open PRs for prod-beta and prod-stable that we will merge on May 6th. Does that work for you?

**Comment by pmuir** [comment]
I think so.

**Comment by tiffanynolan** [comment]
I think that plan should work for us. We would like to have the nav updates related to the App Services bundle released to prod-beta and prod-stable as close to Summit as possible. I think this one is not as critical for us as the other one that @epwinchell is working on: https://github.com/RedHatInsights/cloud-services-config/pull/1082

**Pull request merged**
