### PR TITLE
ROS api routes getting upgraded from v0 to v1

### PR DESCRIPTION
**Pull request by saltgen**
We are planning for GA very soon, our API endpoints are now v1, deployment pending.

References:

https://issues.redhat.com/browse/RHIROS-426

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@saltgen as this will affect only pre-prod envs I assume it can be safely merged before the GA release?

**Comment by apuntamb** [comment]
@Hyperkid123 We have changes available on CI and QA, so does it make sense to raise and merge PRs against ci/qa-stable/beta these four environments?

**Comment by Hyperkid123** [comment]
@apuntamb this PR will affect ci/qa/stable beta environments only. If you want to change the same change in the stable you have to make the same changes in `ci-stable` and `stage-stable` branches in this repository.

**Comment by apuntamb** [comment]
> @apuntamb this PR will affect ci/qa/stable beta environments only. If you want to change the same change in the stable you have to make the same changes in `ci-stable` and `stage-stable` branches in this repository.

@Hyperkid123 you mean ci/qa/**stage** beta environments only?
So, will this PR be enough for qa and stage beta also? 
I thought we should open separate PRs for `ci-beta`, `ci-stable`, `qa-beta`, `qa-stable`, `stage-beta`, `stage-stable`, `prod-beta`, `prod-stable`

**Comment by Hyperkid123** [comment]
> So, will this PR be enough for qa and stage beta also?

@apuntamb yes.

> I thought we should open separate PRs for ci-beta, ci-stable, qa-beta, qa-stable, stage-beta, stage-stable, prod-beta, prod-stable

As the pre-prod evs use the same builds, there is some synchronization going on. The only envs that are not synced at all are `prod-beta`, `prod-stable` and `stage-stable`.

**Comment by saltgen** [comment]
Thanks @Hyperkid123 for the pointers! :raised_hands: 

@karelhala / @ryelo I hope this one is good to go, additionally I have raised another similar one
for `stage-stable`, [here](https://github.com/RedHatInsights/cloud-services-config/pull/1006), thanks!

**Pull request merged**
