### PR TITLE
Add new Downloads page to OCM left navigation

### PR DESCRIPTION
**Pull request by cben**
- [x] ~~Don't merge yet, the version currently in production https://cloud.redhat.com/openshift/downloads is older but we should get a good-to-launch version after today's OCM UI deploy~~...

https://issues.redhat.com/browse/SDA-4211

### CODE REVIEW

**Comment by cben** [comment]
The new page is live in prod, this is good to go.  @karelhala @Hyperkid123 please review.

**Comment by karelhala** [comment]
@cben can you open PRs to all envs as well? We are in middle of migrating to new navigation so other envs are using older config.

**Comment by cben** [comment]
Sure.  The envs we use for OCM:
- qa-beta (https://qaprodauth.cloud.redhat.com/beta/openshift/downloads) — will it sync from ci-beta as README says? #718 
- qa-stable (https://qaprodauth.cloud.redhat.com/openshift/downloads) #701
- prod-beta (https://cloud.redhat.com/beta/openshift/downloads) #702
- prod-stable (https://cloud.redhat.com/openshift/downloads) #703

Any other branch to update?

**Comment by karelhala** [comment]
@cben not sure if you are using `stage` env. But if not, then it's just fine to add to the listed envs.

**Pull request merged**
