### PR TITLE
feat(navbar): new navbar set up

### PR DESCRIPTION
**Pull request by adonispuente**
In accordance with these [mocks](https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/L4OJZAQ), and the exception of inventory groups, try smart managment, and learning resources (all non-complete), these are the new navbar changes

### CODE REVIEW

**Comment by adonispuente** [comment]
I was trying to take some load off platform with this but I have a question regarding steps moving forward. The checks are failing because of the new schema required from the docs. The checks want me to add href's and app Id's to nav list that are embedded in another nav list. Wont this cause users to be directed somewhere onClick even though the item is intended as a dropdown?

**Comment by Hyperkid123** [comment]
@adonispuente I see you have multple nested items in your nav. This is not supported by the PF navigation components. Can you provide mocks? We might have to rope in UX.

**Comment by adonispuente** [comment]
Hey, yeah. These are the links for the new nav
 https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/L4OJZAQ

**Comment by karelhala** [comment]
@adonispuente this is a bit more tricky, than just changing the config. We'll have to go trough the nav changes in chrome in order to support terciary navigation.

Moreover we're moving to the new repository so we have simpler way of serving this file https://github.com/RedHatInsights/chrome-service-backend

Thank you for bringing this to our attention! We'll discuss with our PM how crutial this is so it will be added to our roadmap so we could update the chroming navigation and then bring this over to the chroming service backend.

**Comment by adonispuente** [comment]
@karelhala I see, I'll go ahead and close this PR then. Hopefully it wont be too difficult to implement

**Pull request closed without merging**
