### PR TITLE
chore: add cos-ui

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
We'll also need the repo creating on RedHatInsights - can you make me and @riccardo-forina admins on it?

**Review by karelhala — COMMENTED** [review]
@pmuir does the navigation for `Connectors` use https://github.com/RedHatInsights/cos-ui-build static files? If so, we should change the line 693 to just `id: cos` and lines 710-713 to:

```yml
cos:
  frontend:
    title: Connectors
    deployment_repo: https://github.com/RedHatInsights/cos-ui-build
    paths:
      - /application-services/cos
```

**Comment by karelhala** [comment]
The repo is created, however I am unable to assign you @pmuir or @riccardo-forina because you are not members of RedHatInsights org.

**Comment by pmuir** [comment]
Weird, it's worked on other repos - do you know how to get an invite?

**Comment by pmuir** [comment]
> @pmuir does the navigation for `Connectors` use https://github.com/RedHatInsights/cos-ui-build static files? If so, we should change the line 693 to just `id: cos` and lines 710-713 to:
> 
> ```yaml
> cos:
>   frontend:
>     title: Connectors
>     deployment_repo: https://github.com/RedHatInsights/cos-ui-build
>     paths:
>       - /application-services/cos
> ```

No. (It will be consumed as a federated module like kas-ui etc.)

**Pull request merged**
