### PR TITLE
Add Strimzi UI

### PR DESCRIPTION
**Pull request by b1zzu**

### CODE REVIEW

**Comment by b1zzu** [comment]
cc @pmuir

**Comment by pmuir** [comment]
I just want to check that this won't cause the app to appear in the menus...

**Comment by b1zzu** [comment]
@pmuir any update? can we add it in this way without it appearing in the menus?

**Comment by pmuir** [comment]
Sorry, bad english - I mean - "before we merge this, are we sure that it won't cause the app to appear in the menus... I don't think it will but a maintainer should confirm.

**Comment by kruai** [comment]
@pmuir @b1zzu Adding this won't flat-out add it to any menus. You'll need to add its ID to another app's `sub_apps` for that

**Pull request merged**
