### PR TITLE
Adds topics nav

### PR DESCRIPTION
**Pull request by AllenBW**
in support of https://projects.engineering.redhat.com/browse/RHCLOUD-544
needs https://github.com/RedHatInsights/insights-advisor-frontend/pull/380 to be merged first

### CODE REVIEW

**Comment by AllenBW** [comment]
Because #21 was closed

**Comment by AllenBW** [comment]
Waiting for bu approval before this can go liveeee

**Review by kruai — APPROVED** [review]
Looks good!

**Comment by AllenBW** [comment]
Snap! lets not push this further than ci till the BU wants to release this into the wild 😬 🤗

**Comment by kruai** [comment]
Oh! Since https://github.com/RedHatInsights/insights-advisor-frontend/pull/380 was already merged, and since there wasn't an in-progress or WIP label or indication in the title, I figured it was ready to go. But yeah, it won't get promoted to any other environments until you ask for it.

**Comment by AllenBW** [comment]
<3 thanks! 👌

**Pull request merged**
