### PR TITLE
[ci-beta] Catalog - Add order_processes left nav

### PR DESCRIPTION
**Pull request by lgalis**
Screenshot from 2020-07-17 08-53-17

### CODE REVIEW

**Comment by lgalis** [comment]
@Hyperkid123  - please review

**Comment by gmcculloug** [comment]
@lgalis Let's move `Order Processes` up one item so it is directly under `Platforms`.  This helps keep the items you configure together and keeps `Order` and `Approval` together at the bottom regardless of the persona.

**Review by Hyperkid123 — COMMENTED** [review]
The config is correct. I think we can merge it once the link is in the right place.

**Comment by gmcculloug** [comment]
**Note:** When this is ready to merge we should deploy to ci-beta and qa-beta for now until the rest of the UI and API are further along.  There is a considerable amount of work remaining in both areas before I think this is ready for prod-beta.

**Comment by lgalis** [comment]
@gmcculloug @Hyperkid123 - moved order processes under platforms. Screenshot updated.

**Review by kruai — APPROVED** [review]
Looks good to me. @Hyperkid123 & @gmcculloug I'm taking your "thumbs up" to be an implicit approval and am merging this :)

**Pull request merged**
