### PR TITLE
[prod-beta] Add ansible dashboard

### PR DESCRIPTION
**Pull request by lgalis**

### CODE REVIEW

**Comment by lgalis** [comment]
@karelhala - please review

**Review by karelhala — APPROVED** [review]
We didn't pushed the chrome related PRs to prod-stable. But planning to do so next week, let's postpone this PR until then (otherwise the navigation would be broken)

**Comment by jonnyfiveiq** [comment]
Is the platform in a state whereby this PR can be merged without breaking things?  We are needing this to complete marketing activities, thanks

**Comment by karelhala** [comment]
@jonnyfiveiq yup, the prod-beta has been released yesterday. Merging.

**Pull request merged**
