### PR TITLE
Add to settings menu and add insights submenu

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Review by kruai — CHANGES_REQUESTED** [review]
@josejulio The order of sub-apps in settings is different from CI/QA/Stage. The order in Stage is:
```
    sub_apps:
      - id: my-user-access
        default: true
      - id: rbac
      - id: sources
      - id: integrations
      - id: notifications
      - id: sed
      - id: applications
```

**Comment by josejulio** [comment]
> @josejulio The order of sub-apps in settings is different from CI/QA/Stage. The order in Stage is:

good catch, thanks!

**Review by kruai — APPROVED** [review]
LGTM!

**Comment by kruai** [comment]
There's a freeze on ci-beta at the moment, and I know this is for prod-beta, but... I'd lke to wait until the Summit demo recordings are complete (~2pm) to merge this. Is that all right with you?

**Comment by josejulio** [comment]
> There's a freeze on ci-beta at the moment, and I know this is for prod-beta, but... I'd lke to wait until the Summit demo recordings are complete (~2pm) to merge this. Is that all right with you?

That's fine for me. Actually we have a issue right now. I think it would be better to merge this after that other is solved.

I'll mark this PR as a draft until then.

**Comment by josejulio** [comment]
@kruai @ryelo This is ready to be merged now, thanks!

**Pull request merged**
