### PR TITLE
Add Resource Optimization to prod-stable for GA

### PR DESCRIPTION
**Pull request by PreetiW**
~~We are planning to move Resource Optimization to GA soon and hence opening this draft PR. Once we have the final date for GA will inform the team for review and merge.~~

We want to release Resource Optimization to GA today, can you please review and merge this PR?
**Note:** 
The [Jenkins build (prod-stable)](https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/job/insights-frontend-deployer/job/ros-frontend-build/job/prod-stable/) for Resource Optimization is green 💯

### CODE REVIEW

**Review by PreetiW — COMMENTED** [review]
@Hyperkid123 @karelhala I wanted to know how long it will take for changes to be available in the production website after merging this PR? Is there any way to check the  status of Jenkins jobs linked to the deployment? I tried to access the link mentioned in README but I am getting 404 (I guess its because I don't have the permission)

**Comment by Hyperkid123** [comment]
@PreetiW it usually takes around 10-20 minutes for the deployment to happen.  You can monitor this Job: https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/job/Cloud%20Services%20Config/job/cloud-services-config/

As the ROS frontend is being added to the UI and not updated, you can safely deploy the ROS UI to production in an advance. The files will be sitting in CND and it will be accessible via UI once the CSC is deployed. I would even advise you to first deploy the UI assets ad only then deploy the CSC to avoid potential issues with the akamai cache.

**Comment by PreetiW** [comment]
> @PreetiW it usually takes around 10-20 minutes for the deployment to happen. You can monitor this Job: https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/job/Cloud%20Services%20Config/job/cloud-services-config/

Thank you for sharing the link, I can access the jobs


> As the ROS frontend is being added to the UI and not updated, you can safely deploy the ROS UI to production in an advance. The files will be sitting in CND and it will be accessible via UI once the CSC is deployed. I would even advise you to first deploy the UI assets ad only then deploy the CSC to avoid potential issues with the akamai cache.

@Hyperkid123 Can you please share more information on how one can first deploy the UI assets only and the steps which will be needed to deploy the CSC. Thank you for your help!

**Comment by Hyperkid123** [comment]
> @Hyperkid123 Can you please share more information on how one can first deploy the UI assets only and the steps which will be needed to deploy the CSC. Thank you for your help!

@PreetiW  It's fairly simple. In your app repository create a `prod-stable` branch from one of your other branches (probably `prod-beta`) and that is it.

The rest is automated. After your travis (or other CI) job on the `prod-stable` branch is finished, your app build repository should be updated, If it doesn't already exist, a new `prod-stable` branch will be created in your build repository. Once that is done Jenkins job will run and it will deploy the production assets to Akamai. You should be able to monitor the Jenkins Job here: https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/job/insights-frontend-deployer/job/ros-frontend-build/. Once a `prod-stable` is visible in the UI and the build was successful the assets are on Akamai.

If the Jenkins is not triggered, you can click the `scan repository` button in the left menu. If you don't have rights to trigger it, just ping me on slack and I can do it.

**Comment by PreetiW** [comment]
> > @Hyperkid123 Can you please share more information on how one can first deploy the UI assets only and the steps which will be needed to deploy the CSC. Thank you for your help!
> 
> @PreetiW It's fairly simple. In your app repository create a `prod-stable` branch from one of your other branches (probably `prod-beta`) and that is it.
> 
> The rest is automated. After your travis (or other CI) job on the `prod-stable` branch is finished, your app build repository should be updated, If it doesn't already exist, a new `prod-stable` branch will be created in your build repository. Once that is done Jenkins job will run and it will deploy the production assets to Akamai. You should be able to monitor the Jenkins Job here: https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/job/insights-frontend-deployer/job/ros-frontend-build/. Once a `prod-stable` is visible in the UI and the build was successful the assets are on Akamai.
> 
> If the Jenkins is not triggered, you can click the `scan repository` button in the left menu. If you don't have rights to trigger it, just ping me on slack and I can do it.

This makes things more clear for me from deployment side, thank you so much for the detailed explanation @Hyperkid123 . One last query so once the assets are on Akamai, after that whenever we want to go GA, the only thing which will be needed is to have this PR merged and then it will be shown on console production website correct?

Also this PR is a one time action, once its merged every push to prod-stable branch in [ros-frontend repo](https://github.com/RedHatInsights/ros-frontend) will automatically deploy the changes to console production once all the jobs passes successfully. Did I get it right?

**Comment by Hyperkid123** [comment]
>  after that whenever we want to go GA, the only thing which will be needed is to have this PR merged and then it will be shown on console production website correct?

Yes the CSC PR exposes the assets in the chrome.

> Also this PR is a one time action, once its merged every push to prod-stable branch in ros-frontend repo will automatically deploy the changes to console production once all the jobs passes successfully. Did I get it right?

Exactly. You have to change the CSC only when you need to change the navigation or the module definition.

**Review by Hyperkid123 — APPROVED** [review]

**Comment by pgarciaq** [comment]
+1

**Comment by gnurag** [comment]
+1

**Pull request merged**
