### PR TITLE
Remove my namespaces from navigation config

### PR DESCRIPTION
**Pull request by karelhala**
### No need for my namespaces in navigation for ansible

Since we no longer need my namespaces in navigation, let's remove them.

ping @himdel

### CODE REVIEW

**Comment by himdel** [comment]
Ah, this certainly explains why #994 or #998 didn't do anything, thanks! :) :+1: 

Looks like `My Namespaces` are only present in `qa-stable` & `stage-stable`, looks like this should take care of both? :)

**Review by Hyperkid123 — APPROVED** [review]

**Comment by himdel** [comment]
@Hyperkid123, @karelhala anything I can do to get this finished please? I'm still seeing this on stage-stable, https://github.com/RedHatInsights/cloud-services-config/blob/stage-stable/chrome/ansible-navigation.json#L27-L32

**Comment by Hyperkid123** [comment]
@himdel should be OK now. It will take a few moments to sync on akamai.

**Comment by himdel** [comment]
Thanks, that worked! :)

**Pull request merged**
